sudo: required

language: javascript

branches:
  only:
    - master
    - development

services:
  - docker

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --pull --build-arg APP_ENV=production -t babili/pusher:latest ./;
    docker push babili/pusher:latest;
    else
    docker build --pull --build-arg APP_ENV=development -t babili/pusher:release-candidate ./;
    docker push babili/pusher:release-candidate;
    fi
