FROM node:24.21.0-trixie-slim@sha256:8ec5d7557396cfe32d21c3f9c13072355ceab22b584578ca4bb28af31120cffe AS build

WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force


FROM node:24.21.0-trixie-slim@sha256:8ec5d7557396cfe32d21c3f9c13072355ceab22b584578ca4bb28af31120cffe

RUN apt-get update && \
  apt-get upgrade -y && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /usr/local/lib/node_modules /usr/local/bin/npm /usr/local/bin/npx /usr/local/bin/corepack /opt/yarn-* /usr/local/bin/yarn /usr/local/bin/yarnpkg && \
  find / -xdev -perm /6000 -type f -exec chmod a-s {} +

WORKDIR /usr/src/app
COPY --from=build /usr/src/app/node_modules node_modules
COPY package.json babili_pusher.js ./
COPY app app
COPY config config

ARG APP_ENV=development
ENV NODE_ENV=${APP_ENV}

USER node
CMD ["node", "babili_pusher.js"]
